### ISSUE TITLE
服务端停止后MCDR无法正常退出

### ISSUE THREAD

**Issue by MCsentic** [hanbings/MCDRClear#1]
在控制台输入stop停止服务端后，MCDR检测到服务端停止之后就没反应了
猜测是while true和sleep的问题？

**Comment by hanbings** [comment]
好的，我已经收到了这个issue
将会在下一次更新中尝试修复这个问题(这周星期六或更早)
如果可以，请提供一份复现过程的log，这会对修复它有帮助，谢谢
在修复前此issue将保持Open

**Comment by hanbings** [comment]
另外，很感谢您提出的issue
如果您有兴趣对这个漏洞进行修复
请尽情PR，谢谢您的支持

**Comment by MCsentic** [comment]
很抱歉这么久才回复，刚现场截了下log

**Comment by hanbings** [comment]
下午好，这个问题是由于MCDR最近引入的线程池技术导致，在最新的MCDR-0.9.3 alpha中已经修复这个问题，请尝试更新MCDR再检查一次问题是否存在，谢谢您的支持
